extends Node

const SCREEN_WIDTH := 1280
const SCREEN_HEIGHT := 720

const GRID_SIZE := 6
const TASK_COUNT := 3
const SEARCH_ROOM_COUNT := 1
const CHEST_COUNT := 3
const ELITE_ROOM_COUNT := 2
const BOSS_ROOM_COUNT := 1
const OBSTACLE_COUNT := 7

const BATTLE_DURATION := 30.0
const TASK_DURATION := BATTLE_DURATION
const ALTAR_CHALLENGE_DURATION := 20.0
const EXTRACTION_COUNTDOWN := 3.0
const DIFFICULTY_STEP_SECONDS := 10.0

const SIGNAL_RADIUS := 300.0
const SIGNAL_STABLE_RATIO := 0.6
const SIGNAL_WEAK_RATIO := 0.8

const PLAYER_SPEED := 180.0

const SYNC_MAX := 100.0
const SYNC_MIN_RECOVER_AFTER_DISCONNECT := 20.0
const SYNC_REGEN_DELAY := 3.0
const SYNC_REGEN_PER_SECOND := 3.0
const SYNC_EDGE_DRAIN_PER_SECOND := 2.0

const SMALL_ENEMY_HP := 10.0
const SMALL_ENEMY_SPEED := 55.0
const SMALL_ENEMY_DAMAGE := 5.0
const SMALL_ENEMY_SPAWN_INTERVAL := 1.0
const FIRST_DIFFICULTY_SPAWN_MULTIPLIER := 1.5
const SECOND_DIFFICULTY_SPAWN_CHANCE := 0.35
const WEAPON_LEVEL_SECOND_DIFFICULTY_CHANCE_BONUS := 0.03
const ENEMY_DIFFICULTY_HP_MULTIPLIER := 0.35
const ENEMY_DIFFICULTY_SPEED_MULTIPLIER := 0.12
const ENEMY_CONTACT_COOLDOWN := 0.7

const ELITE_HP := 300.0
const ELITE_SPEED := 35.0
const ELITE_DAMAGE := 15.0
const ELITE_GOLD := 40
const ELITE_SPAWN_TIME := 45.0

const BOSS_HP := 900.0
const BOSS_SPEED := 28.0
const BOSS_DAMAGE := 25.0
const BOSS_GOLD := 120

const AURA_RADIUS_LV := [0.0, 80.0, 100.0, 120.0]
const AURA_DAMAGE_LV := [0.0, 2.5, 3.0, 3.5]
const AURA_TICK_LV := [0.0, 0.5, 0.45, 0.4]

const PROJECTILE_COUNT_LV := [0, 1, 2, 3]
const PROJECTILE_DAMAGE_LV := [0.0, 10.0, 12.0, 18.0]
const PROJECTILE_COOLDOWN_LV := [0.0, 1.2, 1.1, 1.0]
const PROJECTILE_SPEED := 360.0

const BEAM_RANGE := SIGNAL_RADIUS
const BEAM_DAMAGE_LV := [0.0, 2.5, 3.0, 3.5]
const BEAM_TICK_LV := [0.0, 0.25, 0.225, 0.2]

const SHAPE_DAMAGE_LV := [0.0, 8.0, 10.0, 12.0]
const SHAPE_COOLDOWN_LV := [0.0, 2.0, 1.5, 1.0]
const SHAPE_DURATION := 0.4

const SMALL_ENEMY_GOLD := 2
const SCORE_SMALL_KILL := 10
const SCORE_ELITE_KILL := 100
const SCORE_SMALL_DROP := SMALL_ENEMY_GOLD
const SCORE_ELITE_DROP := ELITE_GOLD
const COLLECTIBLE_PICKUP_RADIUS := 22.0
const COLLECTIBLE_ATTRACT_RADIUS := 120.0
const COLLECTIBLE_ATTRACT_SPEED := 260.0

const NORMAL_CHEST_COST := 30
const ADVANCED_CHEST_COST := 80
const HEAL_COST := 50
const BATTLE_CHEST_COUNT_MIN := 2
const BATTLE_CHEST_COUNT_MAX := 3
const BATTLE_CHEST_REFRESH_SECONDS := 10.0
const BATTLE_INTERACT_RADIUS := 56.0
const ALTAR_HOLD_SECONDS := 3.0
const EXTRACTION_RADIUS := 70.0

const BASE_WEAPON_SLOTS := 4
const BASE_PASSIVE_SLOTS := 4
const BASE_WEAPON_ID := "projectile"
